apiVersion: apps/v1
kind: Deployment
metadata:
  name: proresume-deployment
  labels:
    app: proresume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proresume
  template:
    metadata:
      labels:
        app: proresume
    spec:
      containers:
        - name: proresume
          image: yashikaa1/proresume:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
