apiVersion: v1
kind: Service
metadata:
  name: yashika-service
spec:
  type: LoadBalancer  # Use NodePort if on Minikube
  selector:
    app: yashika-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 5000  # Match the container port
