apiVersion: v1
kind: Service
metadata:
  name: proresume-service
spec:
  type: NodePort
  selector:
    app: proresume
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
